server:
  port: 9094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: EXPERTISE
  datasource:
    url: jdbc:mysql://localhost:3306/expertisedb?createDatabaseIfNotExist=true
    password: password
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
