server:
  port: 9093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ORDER
  data:
    mongodb:
      uri: mongodb://localhost:27017/consultationorderdb
      host: localhost
      port: 27017
      database: consultationorder
      repositories:
        enabled: true
