server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  servlet:
    multipart:
      max-file-size: 50MB


  datasource:
    url: jdbc:mysql://localhost:3306/profiledb?createDatabaseIfNotExist=true
    password: password
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  application:

    file:
      uploads:
        photos-output-path: ./uploads

    name: BUSINESS
