server:
  port: 9092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  application:
    name: Entrepreneurs
  data:
    mongodb:
      uri: mongodb://localhost:27017/entrepreneursdb
      host: localhost
      port: 27017
      database: entrepreneursdb
      repositories:
        enabled: true